### ISSUE TITLE
Firefox randomly freezes with sidebartabs extension on

### ISSUE THREAD

**Issue by arzu3649** [asamuzaK/sidebarTabs#192] opened 2022-04-23 01:46 UTC
Hey there. I noticed my Firefox randomly freezes if I have SidebarTabs extension on. The freeze is deep, I have to kill firefox from task manager to restore it. It took me a while to isolate which plugin causes it, but it only happens with the Sidebar. Tried all standard troubleshooting like clearing history, removing places.sqllite, turning off hardware acceleration, etc. Happy to do more diagnostics if required. Windows 10.

**Comment by asamuzaK** [comment] 2022-04-24 01:36
Similar issues have been reported recently in other extensions.
From your point of view, does this issue seem similar to those?

* [High CPU usage and freeze when mouse over tab · Issue #3111 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/3111)
* [High CPU usage and freeze when mouse over tab · Issue #611 · mbnuqw/sidebery](https://github.com/mbnuqw/sidebery/issues/611)
* [1765713 - High CPU usage and freeze when tooltip outside of screen](https://bugzilla.mozilla.org/show_bug.cgi?id=1765713)
* [1688998 - Replace empty BeginPaint/EndPaint calls with ValidateRect](https://bugzilla.mozilla.org/show_bug.cgi?id=1688998)

And according to [1764312 - Long startup time until main window appears](https://bugzilla.mozilla.org/show_bug.cgi?id=1764312), backout is requested for Beta and Release.
Has this change on Firefox side made any difference?

**Comment by arzu3649** [comment] 2022-04-26 01:21
Yes, very similar to #3111 and #611.
1) I have noticed it happens only if sidebar is on the right AND
2) It happesn only if I have 
" #TabsToolbar {
  visibility: collapse;
}"
in userChrome.css
Steps to reproduce are the same as for #3111

**Comment by asamuzaK** [comment] 2022-04-26 01:33
There seems to be no fix for Firefox 99
See [1764312 - Long startup time until main window appears](https://bugzilla.mozilla.org/show_bug.cgi?id=1764312#c27)

If possible, can you try with Nightly and see if it's fixed?

**Comment by arzu3649** [comment] 2022-04-26 01:41
Oh, I don't want to move to Nightly. For now, I have moved the sidebar to the left as a temporary workaround. I will test and report it in the next final release.

**Comment by asamuzaK** [comment] 2022-04-26 01:54
Understood.
I'm tracking Bugzilla so it's okay.

**Comment by asamuzaK** [comment] 2022-04-26 20:46
[1765713](https://bugzilla.mozilla.org/show_bug.cgi?id=1765713) was resolved as a duplicate of [1764312](https://bugzilla.mozilla.org/show_bug.cgi?id=1764312).

**Closed by asamuzaK** 2022-04-26 20:46 UTC
Labels: dependency bug
