### ISSUE TITLE
Hide the default tabs

### ISSUE THREAD

**Issue by MasterKia** [asamuzaK/sidebarTabs#203] opened 2022-07-25 12:26 UTC
First of all, thank you for creating this add-on and bringing the vertical tabs feature to Firefox (It was the only thing holding me back from switching to Firefox when I had Vivaldi).

So my question is: Can the add-on hide default tabs which are on top?
I'm aware that it's possible to hide them by modifying the userChrome.css but can it be done via the add-on itself?

Also may I ask why the add-on still has "Experimental" flag in Firefox Store? Because it seems pretty stable to me.

**Comment by MasterKia** [comment] 2022-07-25 12:28
Also for translation, should I create a folder in `/src/_locales` and translate the "messages.json" file?

**Comment by asamuzaK** [comment] 2022-07-25 22:49
It's not possible at the moment.
See [Add ability to hide native tab bars · Issue #5](https://github.com/asamuzaK/sidebarTabs/issues/5)

> why the add-on still has "Experimental" flag in Firefox Store?

Because this extension relies on unstandardized CSS property `-moz-context-properties`, and user need to enable it manually.

> should I create a folder in /src/_locales and translate the "messages.json" file?

PR is always welcome.
However, please keep in mind that I would like you to commit to localization on an ongoing basis, not just once.

I'm closing this issue as a dupe of #5.

**Closed by asamuzaK** 2022-07-25 22:49 UTC

**Comment by MasterKia** [comment] 2022-07-26 01:56
> please keep in mind that I would like you to commit to localization on an ongoing basis, not just once.

Of course, how should I get notified about new strings?
I could only think of "Watching" this repo for any commits.



> 'm closing this issue as a dupe

Sorry about the duplicate, before creating this issue I manually read all previous issues' titles but it seems I've missed that one.

**Comment by asamuzaK** [comment] 2022-07-26 13:51
> how should I get notified about new strings?

I'll send a mention when updates to the localization are needed.
